server:
  port: 8083
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: prasadbhanu7744@gmail.com
    password: njxanciokstqbbix
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
