spring :
  application :
    name: eureka-service
server :
  port : 8761
eureka :
  client :
    fetchRegistry : false
    registerWithEureka : false
  cloud :
    discovery :
      enabled : true
  instance :
    hostname : localhost

